const state = { section: 'dashboard', stopped: false, suggestion: '', captured: '' };
const view = document.querySelector('#view');
const notice = document.querySelector('#notice');
const title = document.querySelector('#page-title');

const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
function flash(message, danger = false) { notice.hidden = false; notice.className = `notice ${danger ? 'danger' : ''}`; notice.textContent = message; window.setTimeout(() => { notice.hidden = true; }, 4500); }
function card(label, value, detail = '') { return `<article class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(detail)}</small></article>`; }
function render() {
  title.textContent = state.section[0].toUpperCase() + state.section.slice(1);
  const stopped = state.stopped;
  if (state.section === 'dashboard') view.innerHTML = `<div class="welcome"><div><span class="eyebrow">CONTROLLED ASSISTANCE</span><h2>Work with confidence.</h2><p>Nexa helps you prepare professional responses while you keep complete control. Nothing is sent automatically.</p></div><span class="shield">✓</span></div><div class="metrics">${card('WhatsApp Desktop', 'Not tested', 'Real Windows UI Automation required')}${card('Connector capability', 'Not tested', 'Run the capability probe first')}${card('OpenAI', 'Not configured', 'Configure securely in Settings')}${card('Current mode', 'Manual Mode', 'No monitoring is active')}${card('Suggestions today', '0', 'Local activity count')}${card('Message safety', 'Not sent', 'Human approval always required')}</div><div class="section-grid"><section class="panel"><div class="panel-head"><h3>First steps</h3><span class="tag">Phase 1</span></div><ol class="steps"><li><b>01</b><span>Open WhatsApp Desktop and keep it in its normal window.</span></li><li><b>02</b><span>Review independent permissions in WhatsApp.</span></li><li><b>03</b><span>Capture or paste a message in Assistant.</span></li><li><b>04</b><span>Edit, copy, and send manually from WhatsApp.</span></li></ol></section><section class="panel"><div class="panel-head"><h3>Safety status</h3><span class="pill ${stopped ? 'red' : 'green'}">${stopped ? 'Emergency stopped' : 'Protected'}</span></div><p class="muted">Nexa does not press Send, simulate Enter, open conversations, or send messages automatically.</p><div class="rule-list"><span>✓ Human approval required</span><span>✓ API key stays in the main process</span><span>✓ WhatsApp Web is not used</span></div></section></div>`;
  else if (state.section === 'assistant') view.innerHTML = `<div class="section-grid assistant-grid"><section class="panel"><div class="panel-head"><h3>Conversation context</h3><span class="pill blue">Manual Mode</span></div><p class="muted">Use selected text or paste a message. Active-conversation reading remains unavailable until permissions and a real capability probe pass.</p><textarea id="context" class="editor" maxlength="12000" placeholder="Paste the message or context here…">${esc(state.captured)}</textarea><div class="button-row"><button class="secondary" data-action="capture">Capture active conversation</button><button class="primary" data-action="prepare">Confirm context</button></div></section><section class="panel"><div class="panel-head"><h3>Suggested response</h3><span class="pill amber">Not sent</span></div><textarea id="suggestion" class="editor suggestion" maxlength="12000" placeholder="Your approved suggestion will appear here…">${esc(state.suggestion)}</textarea><div class="button-row"><button class="secondary" data-action="copy" ${state.suggestion ? '' : 'disabled'}>Copy</button><button class="primary" data-action="draft" ${state.suggestion ? '' : 'disabled'}>Insert as draft</button></div><small class="muted">Insert as draft is disabled until the Windows bridge verifies a safe structured write.</small></section></div>`;
  else if (state.section === 'whatsapp') view.innerHTML = `<div class="panel"><div class="panel-head"><div><h3>WhatsApp Desktop connector</h3><p class="muted">Official desktop application only · no browser session</p></div><span class="pill amber">Not tested</span></div><div class="connector-status"><div class="connector-icon">◌</div><div><strong>Implementation verified</strong><p class="muted">Real WhatsApp environment not yet tested</p></div></div><div class="probe-grid">${card('Application', 'Not detected', 'Bridge integration pending')}${card('Window', 'Unknown', 'No UI Automation session')}${card('Capability probe', 'Not run', 'Never assume Ready from mocks')}</div><div class="button-row"><button class="primary" data-action="probe">Run capability probe</button><button class="secondary" data-action="diagnostic">Export redacted diagnostics</button></div></div>`;
  else if (state.section === 'activity') view.innerHTML = `<div class="panel"><div class="panel-head"><h3>Activity</h3><span class="tag">Redacted log</span></div><div class="empty"><strong>No activity yet</strong><p>Connector, capture, suggestion, copy, and safety events will appear here without message content.</p></div></div>`;
  else if (state.section === 'settings') view.innerHTML = `<div class="settings-grid"><section class="panel"><h3>OpenAI security</h3><p class="muted">The key is encrypted with the operating system secure storage. It is never returned to this window.</p><input id="api-key" class="input" type="password" autocomplete="off" placeholder="Paste API key to store securely"><div class="button-row"><button class="primary" data-action="save-key">Save securely</button><button class="secondary" data-action="clear-key">Remove key</button></div></section><section class="panel"><h3>Independent permissions</h3><label class="check"><input type="checkbox" checked disabled> Detect WhatsApp status</label><label class="check"><input type="checkbox"> Detect active conversation</label><label class="check"><input type="checkbox"> Read visible conversation</label><label class="check"><input type="checkbox"> Insert approved drafts</label><p class="muted">All sensitive permissions are off by default.</p></section></div>`;
  else if (state.section === 'diagnostics') view.innerHTML = `<div class="section-grid"><section class="panel"><h3>Application information</h3><div class="detail-list"><span>Product<strong>Nexa Desktop Secretary AI Pro</strong></span><span>Version<strong>0.1.0</strong></span><span>Platform<strong>Windows x64 target</strong></span><span>Bridge<strong>Not installed / not tested</strong></span><span>Database<strong>Local configuration active</strong></span></div></section><section class="panel"><h3>Privacy report</h3><p class="muted">Diagnostics are designed to exclude API keys, tokens, message bodies, and complete phone numbers.</p><button class="secondary" data-action="diagnostic">Export redacted diagnostics</button></section></div>`;
  else view.innerHTML = `<div class="panel about"><span class="eyebrow">NEXA DESKTOP SECRETARY AI PRO</span><h2>Professional assistance. Human control.</h2><p class="muted">Version 0.1.0 · Phase 1 · Windows 10/11 x64</p><p>This release focuses on safe collaboration with the official WhatsApp Desktop application. CRM, documents, calls, email, SMS, Telegram, billing, licensing, subscriptions, and production updating remain outside Phase 1.</p></div>`;
  bindActions();
}
function bindActions() {
  document.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', async () => {
    const action = button.dataset.action;
    if (action === 'capture') { flash('Active conversation capture requires explicit permission and a verified Windows bridge. Paste manually for now.'); return; }
    if (action === 'prepare') { state.captured = document.querySelector('#context').value.trim(); if (!state.captured) return flash('Add or paste context before confirming.', true); state.suggestion = 'Suggested response: Thank you for your message. I will review the details and get back to you shortly.'; render(); flash('Context confirmed. Review and edit the suggestion before copying.'); }
    if (action === 'copy') { state.suggestion = document.querySelector('#suggestion').value; await window.nexa.copyText(state.suggestion); flash('Copied to clipboard. Not sent.'); }
    if (action === 'draft') flash('Draft insertion is unavailable until the real UI Automation capability probe passes. Copy and paste manually.', true);
    if (action === 'probe') flash('Capability probe requires the Windows Accessibility Bridge and a real WhatsApp Desktop session.', true);
    if (action === 'diagnostic') flash('Redacted diagnostic export will be available after the bridge is installed.');
    if (action === 'save-key') { try { await window.nexa.setApiKey(document.querySelector('#api-key').value); flash('API key stored in Windows secure storage.'); } catch (error) { flash(error.message, true); } }
    if (action === 'clear-key') { await window.nexa.clearApiKey(); flash('Stored API key removed.'); }
  }));
}
document.querySelectorAll('.nav-item').forEach(button => button.addEventListener('click', () => { state.section = button.dataset.section; document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item === button)); render(); }));
document.querySelectorAll('[data-nexa-action="emergency-stop"]').forEach(button => button.addEventListener('click', async () => { await window.nexa.emergencyStop(); state.stopped = true; document.querySelector('#global-status').textContent = 'Emergency stopped'; flash('Emergency Stop active. All Nexa operations are blocked.', true); render(); }));
window.nexa.onEvent(event => { if (event.type === 'emergency-stop') { state.stopped = true; render(); } });
window.nexa.getState().then(remote => { state.stopped = remote.stopped; render(); });
